# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacob N Langley
subtitle: on development | on writing | on illustration
email: jacob@jacobnlangley.com
profession: front-end web developer
description: > # this means to ignore newlines until "baseurl:"
  I am Front-End Web Developer living in Atlanta GA. Proficient in: HTML5, CSS3, jQuery, Javascript, AJAX, JSON, PHP, Wordpress, Magento.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jacobnlangley.com" # the base hostname & protocol for your site
treehouse_username: 
github_username:  jacobnlangley
codepen_username:  jacobnlangley

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "images/8-bit Jacob.jpeg"

# Build settings
markdown: kramdown

#paginate
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
